---
title: This is a Colab Notebook!
jupyter: python3
---

The first thing you will want to do is import the libraries we use to work with data. **Pandas** loads and manipulates tables of data, **Matplotlib** draws charts, and **Seaborn** is a charting library built on top of Matplotlib that makes good-looking charts with very little code.

To use the functions in our code, we give the libraries short nicknames: `pd` for pandas, `plt` for matplotlib, and `sns` for seaborn.

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")   # nice default chart styling
```

A dataframe is a table read from a CSV file. In the statement below, we call the `read_csv()` function in pandas and pass it the location of the CSV file. Here we load the data straight from the web, so there's nothing to download - just run the cell. The function returns a dataframe that we store in the variable `df`.

```{python}
# California housing data (from the 1990 US Census)
df = pd.read_csv("https://drive.google.com/uc?export=download&id=1QFm_7cTiYtGDJkxwhPzXKvqYjTnPoHLN")
```

The dataframe has functions and variables. If you run the `head()` function on the dataframe `df`, it shows the first few rows of the table along with the column names.

```{python}
df.head()
```

We can create different types of charts and graphs with seaborn. The chart below is a **scatter plot** comparing two columns.

1.   Notice the `x` and `y` arguments. Look at the column names above and choose two to compare. Change the argument names to find other interesting relationships.
2.   What do you think the `ax.set()` call does? Change the strings to label the graph you created in step 1.

```{python}
fig, ax = plt.subplots(figsize=(14, 8))
sns.scatterplot(data=df, x="median_house_value", y="median_income", ax=ax)
ax.set(xlabel="Median House Value ($)",
       ylabel="Median Income",
       title="Median House Value vs Median Income")
```
