---
title: '**Dogs Dataset**'
jupyter: python3
---

**IMPORTANT!!** You must run each code block from top to bottom. First, run the import block, then the "Create a dataframe" block, then the "df.columns" block, etc. The code will not execute until you run the block by clicking on the play button. To see the play button, hover over the [ ] in each block.

```{python}
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
```

The data loads straight from the web - just run the cell below, there's nothing to download.

```{python}
# Create a dataframe from our dogs.csv file
df = pd.read_csv("https://drive.google.com/uc?export=download&id=1JB7i-u7q3YpuxihimQG5GiGTKac-_MLj")
```

```{python}
df.columns
```

# **Histogram**

Run the code below to create a histogram showing how dog breeds are distributed across ranges of max weight. Modify the `bins` argument to fine-tune your graph.

Choose other (numeric) columns and bin sizes to discover interesting information. Remember to update the title and axis labels. Answer the questions below (double click on this box to edit):

1. How many bins did you choose and why?


2. What is one question the histogram you created could help answer? Use mathematical terms (percents, counts, averages, ranges, etc.) and correct use of units of measurement (percents, counts, money, prediction scores, etc.)


```{python}
fig, ax = plt.subplots(figsize=(14, 8))
sns.histplot(data=df, x="Max Weight", bins=10, ax=ax)
ax.set(xlabel="Max Weight", ylabel="Count", title="Max Weight of Dog Breeds")
```
