---
title: Beatles Activity Part 2
jupyter: python3
---



```{python}
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
```

**IMPORTANT!!** You must run each code block from top to bottom. First, run the import block, then the "Create a dataframe" block, then the "df.columns" block, etc. The code will not execute until you run the block by clicking on the play button. To see the play button, hover over the [ ] in each block.

Download the [beatles.csv](https://drive.google.com/file/d/1KhZCeU_h8cgLsjgXG1m0lqpykugYC4S_/view) file onto your computer and drag into this Notebook.

```{python}
# Create a dataframe from our csv file
df = pd.read_csv("/content/beatles.csv")
```

```{python}
# Display the column names
df.columns
```

# Part 2:

With your group, list below 2 quantitative questions or predictions you want to investigate using this dataset using only one column of data, and explain why your question is important or significant.

Type your answer:




Modify the code to display graphs for the columns you have chosen for the Scatter Plot and Crosstab Chart below. 

Interpret your charts in mathematical terms (percents, counts, averages, ranges, etc.) Use correct units of measurement (percents, counts, money, prediction scores, etc.)

Questions to answer, depending on the chart type:

1. What is the question you are trying to answer?

2. Choose one of your charts and describe one piece of information someone could learn.

3. What, if any, assumptions are you making when reading the charts?

4. Describe any patterns and what they might mean or indicate.


*Click on the share link at the top right corner of this Notebook and change so 'anyone with the link can view'. Copy the link and post as a comment on the lesson slides.*

# Scatter Plot

Scatter Plots will show relationships between two columns.

Choose 2 numeric columns, or one text and one numeric to display a relationship between them. 

Remember to add strings for the title, you can leave the axis labels blank.

```{python}
# Plot the graph and add labels
df.plot.scatter(x="", y="", figsize=(14,8))

# Add a title and axis labels
plt.xlabel("")
plt.ylabel("")
plt.title("")

# Uncomment the following statements to draw horizontal or vertical lines. 
# Use axvline() for vertical lines.
# plt.axhline(y=-.22, color="r")
# plt.axhline(y=.78, color="r")
```

# Crosstab (Cross-Tabulation) Chart

Crosstab Charts are used to display counts of distict values in one column mapped to values in another column. The chart is displayed in a table format. Only use when the number of distinct values is small, otherwise you will generate a huge table!

You can apply a heatmap to your table to show the higher values. Try changing the color name to find one that works best.

Choose 2 columns to create a crosstab chart. Update the the column name for rows in the 'index' argument, and the other column in the 'columns' argument. 

Add a string to the first print statement to create a title.

```{python}
# Add a title to the chart using Python print() statement
print('\n')

# Adding a heatmap to highlight the higher numbers, you must import
# the import seaborn libarary: import seaborn as sns
orange = sns.light_palette("orange", as_cmap=True)

# Create the crosstab chart, specify two column names: index = the rows, and
# columns = the columns.
pd.crosstab(index=df[''], columns=[df['']]).style.background_gradient(cmap=orange)
```

```{python}
# Use this code to create a crosstab chart without a heatmap to display total counts.

pd.crosstab(index=df[''], columns=[df['']], margins=True)
```

